{% set name = "datasets" %}

package:
  name: "{{ name|lower }}"
  version: "{{ DATASETS_VERSION }}"

source:
  path: ../../

build:
  noarch: python

requirements:
  host:
    - python
    - pip
    - numpy >=1.17
    - pyarrow >=8.0.0
    - python-xxhash
    - dill
    - pandas
    - requests >=2.19.0
    - tqdm >=4.66.3
    - dataclasses
    - multiprocess
    - fsspec
    - huggingface_hub >=0.21.2,<1.0.0
    - packaging
    - aiohttp
  run:
    - python
    - pip
    - numpy >=1.17
    - pyarrow >=8.0.0
    - pyarrow-hotfix
    - python-xxhash
    - dill
    - pandas
    - requests >=2.19.0
    - tqdm >=4.66.3
    - dataclasses
    - multiprocess
    - fsspec
    - huggingface_hub >=0.21.2,<1.0.0
    - packaging
    - aiohttp

test:
  imports:
    - datasets

about:
  home: https://huggingface.co
  license: Apache License 2.0
  license_file: LICENSE
  summary: "🤗 The largest hub of ready-to-use NLP datasets for ML models with fast, easy-to-use and efficient data manipulation tools"
