repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
        types: [python]
        stages: [commit]
        args: ["--config", "pyproject.toml", "tests", "src", "benchmarks", "metrics"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.255'
    hooks:
    - id: ruff
      stages: [commit]
      args: [ "--config", "pyproject.toml", "tests", "src", "benchmarks", "metrics", "--fix"]
