name: Add Dataset
description: Request the addition of a specific dataset to the library
labels: ["dataset request"]
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: Name of the dataset
    validations:
      required: true
  
  - type: input
    id: paper
    attributes:
      label: Paper
      description: Link to the dataset paper if available

  - type: input
    id: data
    attributes:
      label: Data
      description: Link to the Github repository or current dataset location
    validations:
      required: true
  
  - type: input
    id: motivation
    attributes:
      label: motivation
      description: What are some good reasons to have this dataset
    validations:
      required: true

  - type: markdown
    attributes:
      value: Instructions to add a new dataset can be found [here](https://github.com/huggingface/datasets/blob/main/ADD_NEW_DATASET.md).
