name: Bug report
description: Create a report to help reproduce and fix the bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce the bug
      description: |
        Please provide a code sample that reproduces the problem you ran into. It can be a Colab link or just a code snippet.
        If you have code snippets, error messages, stack traces please provide them here as well.
        Important! Use code tags to correctly format your code. See https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting
        Do not use screenshots, as they are hard to read and (more importantly) don't allow others to copy-and-paste your code.
      placeholder: |
        Steps to reproduce the behavior:
          
          1.
          2.
          3.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: A clear and concise description of the expected results.

  - type: textarea
    id: environment-info
    attributes:
      label: Environment info
      description: Please share your environemnt info with us. You can run the command `datasets-cli env` and copy-paste its output below.
      placeholder: datasets version, platform, python version, ...
    validations:
      required: true
