name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-request
    attributes:
      label: Feature Request
      description: A clear and concise description of the feature proposal.
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: A clear and concise description of the solution you'd like to see implemented.
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.
