name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release
      - v*-patch

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@47c6b5880f408881e68ca60fed8c1de1e454eb01  # main
    with:
      commit_sha: ${{ github.sha }}
      package: datasets
      notebook_folder: datasets_doc
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
