name: Release - Conda

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

env: {}

jobs:
  build_and_package:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5  # v4.0.1
        with:
          auto-update-conda: true
          auto-activate-base: false
          python-version: "3.10"
          channels: huggingface

      - name: Setup conda env
        run: |
          # Install conda-build into base so the command is available
          conda install -y -c defaults -c conda-forge anaconda-client conda-build
          # Create the build environment
          conda create -y -n build-datasets python=3.10
          conda activate build-datasets

      - name: Extract version
        run: |
          VERSION=$(python setup.py --version)
          if [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(\.[a-zA-Z0-9]+)?$ ]]; then
            echo "DATASETS_VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "Invalid version format: $VERSION" >&2
            exit 1
          fi

      - name: Build conda packages
        run: |
          conda-build --override-channels -c conda-forge -c huggingface .github/conda

      - name: Upload to Anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          anaconda upload `conda-build .github/conda --output -c conda-forge` --force
