name: Test audio

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsndfile1 sox
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests,audio]
          pip install pyarrow --upgrade
      - name: Test audio with pytest
        run: |
          HF_SCRIPTS_VERSION=master python -m pytest -n 2 -sv ./tests/features/test_audio.py
